name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Lint
      run: npm run lint
    - name: Build & Test
      run: |
        npm run build
        npm run test:ci
    - uses: codecov/codecov-action@v1
      with:
        files: ./coverage/lcov.info
